---

- ansible.builtin.import_playbook: ../container/docker.yml

- hosts: "{{ hostlist | default('all') }}"
  become: yes
  tasks:
    - name: configure prometheus
      ansible.builtin.include_role:
        name: prometheus
